provider: autogen_ext.models.openai.OpenAIChatCompletionClient
component_type: model
version: 1
component_version: 1
description: Chat completion client for OpenAI hosted models.
label: OpenAIChatCompletionClient
config:
  model: gpt-4o-mini
  timeout: 60
  max_tokens: 400
  temperature: 0.3
  frequency_penalty: 0
  presence_penalty: 0
  max_retries: 5


